French ReadMe
pock/pock pull request #423
Opened 2021-01-10 22:09 UTC by TomPlanche

I've made a French translation for Pock's ReadMe

2021-01-15 13:40 UTC, zek0faws commented
I asked for some french typo.

Can you please move your file into '.github/readmes/README.fr.md' and not replace the default README please ?

2021-01-15 13:45 UTC, zek0faws requested changes
I requested typo changes in French.

Can you please move your file into '.github/readmes/README.fr.md' and not replace the default README please ?

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Si vous etes sous macOS Catalina (10.15), clickez [ici](https://pock.dev/docs/catalina.html) et lisez les suggestions pour avoir une expérience sans failles.
êtes *
sans faille. *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +A la fin, chaque widget aura son propre _repo dédié_, ou vous pourriez ouvrir de nouveaux PRs.
À la fin *
où vous pourriez ouvrir de nouvelles Pull-Request *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Les PRs qui sont actuellement ouverts seronts rassemblés manuellement dans le depôt du widget dédié.
Les Pull-Request qui sont actuellement ouvertes *
seront rassemblées *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +<small>Inclus cinq widgets par défault</small>
Comprend cinq widgets par défaut *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Votre dock macOs dans votre Touch Bar, le widget 'core' de base.
macOS *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +##### En cours widget
Widget en cours de lecture

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +| glissé à gauche  | son précédent        |
glisser

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +| glissé à droite  | son suivant          |
glisser

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +| touché           | active le play/pause |
tapoter

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Un widget ESC pratique est là, au cas ou, pour que vous n'ayez pas à cacher Pock pour acceder à celui du système.
au cas où *
pour accéder *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +##### Statut widget
Widget d'état système

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Gardez toujours un œil sur les informations du système, comme l'heure ou peut-être le statut de la Wifi ou celui de la batterie. Configurer les éléments depuis des paramètres.
le Wi-Fi
depuis les paramètres

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Appuyez longuement ou glissez sur l’élément central de commande pour invoquer des curseurs.
Appuyez longuement ou faites glisser sur l'élément central de contrôle pour afficher les curseurs.

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Vous pouvre ajuster les réglages de Pock et des widgets afin de refléter vos besoins spécifiques. Vous pouvez y accèder dans **Preferences**.
Vous pouvez *
Vous pouvez y accéder *

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +Vous pouvez personnaliser la position du widget dans TouchBar depuis **Customize**.
Vous pouvez personnaliser la position du widget dans TouchBar à partir de l'élément de menu **Personnaliser**

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +## Customisation
Personnaliser

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +  Vous pourrez bientot avec <b>PockKit</b>!
bientôt

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +<small>* Certaines traductions peuvent être incomplètes ou incorrectes </small>.
Add : 
🇫🇷 [Français](.github/readmes/README.fr.md)

2021-01-15 13:45 UTC, zek0faws commented on README.md
> +**Pock** ne sera jammais commercialisé.
jamais *

2021-01-15 14:48 UTC, yannicklamprecht requested changes
Please create a French version in the following directory instead: `.github/readmes/`. Modifiying the original global one is not intended as it removes the possibility to understand the original readme.

2021-01-29 13:22 UTC, barchemice commented
> Please create a French version in the following directory instead: `.github/readmes/`. Modifying the original global one is not intended as it removes the possibility to understand the original readme.

I already created a French translation, a couple of months ago. How do you put it in the right repository?
The one proposed above has a lot of mistakes.

2022-01-16 17:26 UTC, closed without merging